Implemented week1 movie app tasks
bhumikama/movie-app pull request #1
Opened 2024-07-04 08:38 UTC by bhumikama

Implemented movie app tasks for week1

1. designed and implemented the layout of the movie card via DOM manipulation.
2. submitting and displaying a comment about the movie. 
3.  rating the movie in a star-rating format and updating the same.

2024-07-04 09:38 UTC, vdaguenet requested changes
Excellent work! Every feature works and you even implemented the bonus part 👏🏼

I am requesting changes because you should have a `form` element for writing a comment. It is a small change but it will have a big impact for the accessibility of your app.

2024-07-04 09:38 UTC, vdaguenet commented on movie.js
> +document.addEventListener("DOMContentLoaded", () => {
You don't need to wait for this event since you included your JS script at the end of the `<body>`.

2024-07-04 09:38 UTC, vdaguenet commented on movie.js
> +    <input type="text" placeholder="comment here ..." class="input-comment" id="input-comment-${movie.id}"/>
You should put the `input` and `button` inside a `form` element. It is more semantically correct, meaning better accessibility. Then, a user can submit a comment by pressing the Enter key or clicking the Submit button. 
You will have to adjust your code and listen to the [submit event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event) of the `form` instead of listening to the click event of the `button`.

2024-07-04 09:38 UTC, vdaguenet commented on movie.js
> +const movieComments = {};
The comments could be an attribute of a film .
```js
{
  id: 123,
  title: "My movie",
  ...
  comments: []
}
```

2024-07-04 09:38 UTC, vdaguenet commented on movie.js
> +    <div class="star-rating">
**Optional comment**
It could be interesting to add the movie ID as a [data attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) (`<div class="star-rating" data-movie-id="123">`) to be able to assign the rating to a movie object. Then, we could imagine calculating the average rating of a movie, sorting movies by their rating, and so on. 

You don't have to change your code based on this comment. I tried it, and it works as expected. I am only giving you an idea of how to prepare your project for future features.

2024-07-04 09:38 UTC, vdaguenet commented on movie.js
> +const movies = [
You could store the movies in a different file to make the main file of your project smaller and easier to read.

2024-07-04 09:48 UTC, bhumikama commented
@vdaguenet ,thanks for your quick review and suggestions. I will make the suggested changes and request for another review.

2024-07-04 16:11 UTC, bhumikama commented
Hi @vdaguenet ,
I have modified the code to include the suggestions. Please have another look and let me know if I need to make any other changes.

Thank you

2024-07-04 18:52 UTC, vdaguenet commented on movie.js
> +import { movies } from "./storemovies.js";
Fancy!

2024-07-04 18:52 UTC, vdaguenet commented on movie.js
> +function displayComments(movieId, movieComment) {
```suggestion
function displayComments(movieId, movieComments) {
```

2024-07-04 18:52 UTC, vdaguenet commented on movie.js
> +    <input type="text" placeholder="comment here ..." class="input-comment" id="input-comment-${movie.id}"/>
Good changes! Don't forget to indent your code, even if it's in a string.

2024-07-04 18:52 UTC, vdaguenet commented on movie.js
> +  const commentInput = document.getElementById(`input-comment-${movieId}`);
IMO this function should be agnostic of the input. You should retrieve the text value in the `submit` event handler and pass it to this function. 

In pseudo code:
```js
function addComment(movieId, commentText) { 
  // 1. Find the movie that matches the movieId
  // 2. Check that the movie exists
  // 3. Add the comment to the movie's comments list
}
```

2024-07-04 21:38 UTC, bhumikama commented
@vdaguenet ,thanks for your feedback.
I have included the suggested modifications to improve the functionality.Please have a look.
Thank you

2024-07-05 06:03 UTC, vdaguenet approved these changes
Great work 👏🏻
Thanks for taking the time to do the adjustments I suggested

2024-07-05 17:47 UTC, bhumikama commented
> Great work 👏🏻 Thanks for taking the time to do the adjustments I suggested

 Thank you ! Appreciate your valuable feedback and suggestions!

2024-07-05 17:47 UTC, merged